#!/usr/bin/python

#Audio Tools, a module and set of tools for manipulating audio data
#Copyright (C) 2007-2011  Brian Langenberger

#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA


import sys
import audiotools
import audiotools.cdio as cdio
import os
import cStringIO
import gettext

gettext.install("audiotools", unicode=True)

if (__name__ == '__main__'):
    parser = audiotools.OptionParser(
        usage=_(u"%prog [-x filename]"),
        version="Python Audio Tools %s" % (audiotools.VERSION))

    parser.add_option(
        '-V', '--verbose',
        action='store',
        dest='verbosity',
        choices=audiotools.VERBOSITY_LEVELS,
        default=audiotools.DEFAULT_VERBOSITY,
        help=_(u'the verbosity level to execute at'))

    parser.add_option(
        '-x', '--xmcd', action='store',
        type='string', dest='xmcd', default='-',
        metavar='FILENAME',
        help=_(u'FreeDB XMCD file or MusicBrainz XML output file'))

    parser.add_option('-A', '--audio-ts', action='store', default=None,
                      type='string', dest='audio_ts', metavar='DIR',
                      help='location of AUDIO_TS directory')

    parser.add_option('--title', action='store', default=1,
                      type='int', dest='title',
                      help='DVD-Audio title number to retrieve metadata for')

    server = audiotools.OptionGroup(parser, _(u"Server Options"))

    server.add_option(
        '--musicbrainz-server', action='store',
        type='string', dest='musicbrainz_server',
        default=audiotools.MUSICBRAINZ_SERVER,
        metavar='HOSTNAME')
    server.add_option(
        '--musicbrainz-port', action='store',
        type='int', dest='musicbrainz_port',
        default=audiotools.MUSICBRAINZ_PORT,
        metavar='PORT')

    server.add_option(
        '--freedb-server', action='store',
        type='string', dest='freedb_server',
        default=audiotools.FREEDB_SERVER,
        metavar='HOSTNAME')
    server.add_option(
        '--freedb-port', action='store',
        type='int', dest='freedb_port',
        default=audiotools.FREEDB_PORT,
        metavar='PORT')

    server.add_option(
        '--no-musicbrainz', action='store_false',
        dest='use_musicbrainz', default=True,
        help='do not query MusicBrainz for metadata')
    server.add_option(
        '--no-freedb', action='store_false',
        dest='use_freedb', default=True,
        help='do not query FreeDB for metadata')

    server.add_option(
        '-D', '--default',
        action='store_const', const=1, default=None,
        help=_(u'when multiple choices are available, ' +
               u'select the first one automatically'))

    parser.add_option_group(server)

    (options, args) = parser.parse_args()
    msg = audiotools.Messenger("dvda2xmcd", options)

    if (options.xmcd == '-'):
        outfile = sys.stdout
    else:
        try:
            outfile = os.fdopen(os.open(options.xmcd,
                                        os.O_WRONLY | os.O_CREAT | os.O_EXCL,
                                        0666 ^ audiotools.get_umask()),
                                "w")
        except OSError, err:
            msg.os_error(err)
            sys.exit(1)

    if (options.audio_ts is None):
        msg.error(
            _(u"You must specify the DVD-Audio's AUDIO_TS directory with -A"))
        sys.exit(1)

    try:
        dvda = audiotools.DVDAudio(options.audio_ts)
    except audiotools.InvalidDVDA, err:
        msg.error(unicode(err))
        sys.exit(1)
    except OSError, err:
        msg.os_error(err)
        sys.exit(1)

    if (options.title < 1):
        msg.error(_(u"title number must be greater than 0"))
        sys.exit(1)
    title = dvda[0][options.title - 1]

    #grab XML/XMCD data from MusicBrainz/FreeDB
    musicbrainz_discid = audiotools.MBDiscID(
        [(track.pts_length * 75) / audiotools.DVDAudio.PTS_PER_SECOND
         for track in title])

    freedb_discid = audiotools.DiscID(
        [(track.pts_length * 75) / audiotools.DVDAudio.PTS_PER_SECOND
         for track in title])

    msg.info(_(u"Found DVD-Audio information"))

    returnval = 0
    musicbrainz_matches = 0
    freedb_matches = 0

    try:
        if (options.use_musicbrainz):
            musicbrainz_matches = audiotools.get_mbxml(
                musicbrainz_discid,
                outfile,
                options.musicbrainz_server,
                options.musicbrainz_port,
                msg,
                options.default)
            returnval = 0
        if ((musicbrainz_matches == 0) and options.use_freedb):
            freedb_matches = audiotools.get_xmcd(
                freedb_discid,
                outfile,
                options.freedb_server,
                options.freedb_port,
                msg,
                options.default)
            returnval = 0
    except Exception, e:
        msg.error(unicode(e))
        outfile.close()
        if (os.path.isfile(options.xmcd)):
            os.unlink(options.xmcd)
        sys.exit(1)

    #if musicbrainz_matches and freedb_matches are both 0
    #output a MusicBrainzReleaseXML file instead of a FreeDB one
    #since XML is better for editing by end users
    #(none of that " / "-handling nonsense)
    if ((musicbrainz_matches == 0) and (freedb_matches == 0)):
        if (options.use_musicbrainz):
            musicbrainz_discid.toxml(outfile)
        else:
            freedb_discid.toxmcd(outfile)

        outfile.close()
        msg.info(_(u"%s written") % (msg.filename(options.xmcd)))
    else:
        outfile.close()
        msg.info(_(u"%s written") % (msg.filename(options.xmcd)))

    if (returnval != 0):
        sys.exit(1)
