#!/usr/bin/python

#Audio Tools, a module and set of tools for manipulating audio data
#Copyright (C) 2007-2013  Brian Langenberger

#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA


import os.path
import audiotools
import audiotools.text as _

if (__name__ == '__main__'):
    parser = audiotools.OptionParser(
        usage=_.USAGE_TRACKINFO,
        version="Python Audio Tools %s" % (audiotools.VERSION))
    parser.add_option("-n", "--no-metadata",
                      action="store_true", dest="no_metadata",
                      default=False)

    parser.add_option("-L", "--low-level",
                      action="store_true", dest="low_level",
                      default=False)

    parser.add_option("-b", "--bitrate",
                      action="store_true", dest="show_bitrate")

    parser.add_option("-%", "--percentage",
                      action="store_true", dest="show_percentage")

    parser.add_option("-C", "--channel-assignment",
                      action="store_true", dest="channel_assignment")

    (options, args) = parser.parse_args()
    msg = audiotools.Messenger("trackinfo", options)

    for file in audiotools.open_files(args, messenger=msg):
        length = int(file.seconds_length())
        if (options.show_bitrate):
            try:
                msg.output(
                    _.LAB_TRACKINFO_BITRATE %
                    {'bitrate': ((os.path.getsize(file.filename) * 8) /
                                 2 ** 10) / length,
                     'filename': audiotools.Filename(file.filename)})
            except ZeroDivisionError:
                msg.output(
                    _.LAB_TRACKINFO_BITRATE %
                    {'bitrate': 0,
                     'filename': audiotools.Filename(file.filename)})
        elif (options.show_percentage):
            try:
                percentage = (float(os.path.getsize(file.filename) * 100) /
                              (file.total_frames() * file.channels() *
                               (file.bits_per_sample() / 8)))
                msg.output(
                    _.LAB_TRACKINFO_PERCENTAGE %
                    {'percentage': int(round(percentage)),
                     'filename': audiotools.Filename(file.filename)})
            except ZeroDivisionError:
                msg.output(_.LAB_TRACKINFO_PERCENTAGE %
                           {'percentage': "0",
                            'filename': audiotools.Filename(file.filename)})
        else:
            msg.output(
                _.LAB_TRACKINFO_ATTRIBS %
                {"minutes": length / 60,
                 "seconds": length % 60,
                 "channels": file.channels(),
                 "rate": audiotools.khz(file.sample_rate()),
                 "bits": file.bits_per_sample(),
                 "filename": audiotools.Filename(file.filename)})
        if (not options.no_metadata):
            metadata = file.get_metadata()
            if (not options.low_level):
                if (metadata is not None):
                    msg.output(unicode(metadata))
                    msg.output(u"")
                replay_gain = file.replay_gain()
                if (replay_gain is not None):
                    msg.output(_.LAB_TRACKINFO_REPLAYGAIN)
                    msg.new_row()
                    msg.output_column(_.LAB_TRACKINFO_TRACK_GAIN, True)
                    msg.output_column(u" : ")
                    msg.output_column(unicode(replay_gain.track_gain) + u" dB")
                    msg.new_row()
                    msg.output_column(_.LAB_TRACKINFO_TRACK_PEAK, True)
                    msg.output_column(u" : ")
                    msg.output_column(u"%f" % (replay_gain.track_peak))
                    msg.new_row()
                    msg.output_column(_.LAB_TRACKINFO_ALBUM_GAIN, True)
                    msg.output_column(u" : ")
                    msg.output_column(unicode(replay_gain.album_gain) + u" dB")
                    msg.new_row()
                    msg.output_column(_.LAB_TRACKINFO_ALBUM_PEAK, True)
                    msg.output_column(u" : ")
                    msg.output_column(u"%f" % (replay_gain.album_peak))
                    msg.output_rows()
                    msg.output(u"")
                cuesheet = file.get_cuesheet()
                if (cuesheet is not None):
                    msg.output(_.LAB_TRACKINFO_CUESHEET)
                    indexes = {}  # track_number -> {index_number -> offset}
                    isrcs = {}    # track_number -> ISRC unicode
                    index_numbers = set([])
                    for track in cuesheet.tracks():
                        track_indexes = {}
                        for index in track.indexes():
                            track_indexes[index.number()] = index.offset()
                            index_numbers.add(index.number())
                        indexes[track.number()] = track_indexes
                        track_isrc = track.ISRC()
                        if (track_isrc is not None):
                            isrcs[track.number()] = \
                                track_isrc.strip(chr(0)).decode('ascii',
                                                                'replace')
                        else:
                            isrcs[track.number()] = u""

                    index_numbers = list(index_numbers)
                    index_numbers.sort()
                    msg.new_row()
                    msg.output_column(u"  ")
                    msg.output_column(_.LAB_TRACKINFO_CUESHEET_TRACK, True)
                    for i in index_numbers:
                        msg.output_column(u"  ")
                        msg.output_column(
                            _.LAB_TRACKINFO_CUESHEET_INDEX % (i), True)
                    msg.output_column(u"  ")
                    msg.output_column(_.LAB_TRACKINFO_CUESHEET_ISRC, True)

                    for t in sorted(indexes.keys()):
                        msg.new_row()
                        msg.output_column(u"")
                        msg.output_column(unicode(t), True)
                        track_indexes = indexes[t]
                        for i in index_numbers:
                            msg.output_column(u"")
                            if (i in track_indexes):
                                index = track_indexes[i]
                                msg.output_column(
                                    audiotools.build_timestamp(
                                        int(index * 75)).decode('ascii'))
                            else:
                                msg.output_column(u"")
                        msg.output_column(u"")
                        msg.output_column(isrcs[i])

                    msg.output_rows()
                    msg.output(u"")
            else:
                if (metadata is not None):
                    msg.output(metadata.raw_info())
                    msg.output(u"")
        if (options.channel_assignment):
            msg.output(_.LAB_TRACKINFO_CHANNELS)

            channel_names = dict(
                [(attr, audiotools.ChannelMask.MASK_TO_NAME[mask])
                 for (attr, mask) in
                 audiotools.ChannelMask.SPEAKER_TO_MASK.items()])

            if (file.channel_mask().defined()):
                for (i, channel) in enumerate(file.channel_mask().channels()):
                    msg.output(_.LAB_TRACKINFO_CHANNEL %
                               {"channel_number": i + 1,
                                "channel_name": channel_names[channel]})
            else:
                for i in xrange(file.channels()):
                    msg.output(_.LAB_TRACKINFO_CHANNEL %
                               {"channel_number": i + 1,
                                "channel_name": _.LAB_TRACKINFO_UNDEFINED})
