#!/usr/bin/python

#Audio Tools, a module and set of tools for manipulating audio data
#Copyright (C) 2007-2013  Brian Langenberger

#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

import sys
import os.path
import audiotools
import audiotools.text as _
from operator import or_

MAX_CPUS = audiotools.MAX_JOBS


class Counter:
    def __init__(self):
        self.value = 0

    def __int__(self):
        return self.value

    def increment(self):
        self.value += 1


class FailedAudioFile:
    def __init__(self, class_name, filename, err):
        self.NAME = class_name
        self.filename = filename
        self.err = err

    def verify(self):
        raise self.err


def open_file(filename):
    #this is much like audiotools.open
    #except that file init errors fail differently

    f = open(filename, "rb")
    try:
        audio_class = audiotools.file_type(f)
        if (((audio_class is not None) and
             (audio_class.has_binaries(audiotools.BIN)))):
            class_name = audio_class.NAME
            try:
                return audio_class(filename)
            except audiotools.InvalidFile, err:
                return FailedAudioFile(class_name, filename, err)
        else:
            raise audiotools.UnsupportedFile(filename)
    finally:
        f.close()


def get_tracks(args, queued_files, accept_list=None):
    if (accept_list is not None):
        accept_list = set(accept_list)

    for path in args:
        if (os.path.isfile(path)):
            try:
                filename = audiotools.Filename(path)
                if (filename not in queued_files):
                    queued_files.add(filename)
                    track = open_file(str(filename))
                    if ((accept_list is None) or (track.NAME in accept_list)):
                        yield track
            except (audiotools.UnsupportedFile, IOError, OSError):
                continue
        elif (os.path.isdir(path)):
            for (d, ds, fs) in os.walk(path):
                for track in get_tracks([os.path.join(d, f) for f in fs],
                                        queued_files,
                                        accept_list=accept_list):
                    yield track


def track_number(track, default):
    metadata = track.get_metadata()
    if (metadata is not None):
        if (metadata.track_number is not None):
            return metadata.track_number
        else:
            return default
    else:
        return default


def verify(progress, track):
    try:
        track.verify(progress)
        return (audiotools.Filename(track.filename), track.NAME, None)
    except audiotools.InvalidFile, err:
        return (audiotools.Filename(track.filename), track.NAME, unicode(err))


class Results:
    def __init__(self, messenger):
        self.msg = messenger
        self.summary_success = {}
        self.summary_failure = {}

    def display(self, result):
        (filename, track_type, error) = result
        if (error is None):
            self.summary_success.setdefault(track_type, Counter()).increment()
            return _.LAB_TRACKVERIFY_RESULT % {
                "path": filename,
                "result": self.msg.ansi(_.LAB_TRACKVERIFY_OK,
                                        [self.msg.FG_GREEN])}
        else:
            self.summary_failure.setdefault(track_type, Counter()).increment()
            return _.LAB_TRACKVERIFY_RESULT % {
                "path": filename,
                "result": self.msg.ansi(error,
                                        [self.msg.FG_RED])}


def accuraterip_checksum(progress, track):
    from audiotools.cdio import ARChecksum

    reader = audiotools.PCMReaderProgress(track.to_pcm(),
                                          track.total_frames(),
                                          progress)
    checksum = ARChecksum()

    try:
        audiotools.transfer_data(reader.read, checksum.update)

        return (audiotools.Filename(track.filename),
                track.NAME,
                checksum.checksum(),
                None)
    except (IOError, ValueError), err:
        return (audiotools.Filename(track.filename),
                track.NAME,
                None,
                str(err))


def accuraterip_image_checksum(progress, track, filename, track_number,
                               pcm_frames_offset, total_pcm_frames):
    from audiotools.cdio import ARChecksum

    reader = track.to_pcm()

    checksum = ARChecksum()

    #if PCMReader has seek(), use it to reduce the amount of frames to skip
    if (hasattr(reader, "seek") and callable(reader.seek)):
        pcm_frames_offset -= reader.seek(pcm_frames_offset)

    reader = audiotools.PCMReaderProgress(
        audiotools.PCMReaderWindow(reader,
                                   pcm_frames_offset,
                                   total_pcm_frames),
        total_pcm_frames,
        progress)

    try:
        audiotools.transfer_data(reader.read, checksum.update)

        return (filename,
                track_number,
                track.NAME,
                checksum.checksum(),
                None)
    except (IOError, ValueError), err:
        return (filename,
                track_number,
                track.NAME,
                None,
                str(err))



class AccurateRipResults:
    def __init__(self, messenger):
        self.msg = messenger
        self.summary_match = {}
        self.summary_mismatch = {}
        self.summary_notfound = {}
        self.summary_error = {}
        self.matches = {}

    def add_matches(self, filename, checksums):
        self.matches[(filename, None)] = checksums[:]

    def display(self, result):
        (filename, track_type, checksum, error) = result
        if (error is None):
            ar_matches = self.matches.get((filename, None), [])
            if (len(ar_matches) == 0):
                self.summary_notfound.setdefault(track_type,
                                                 Counter()).increment()
                return _.LAB_TRACKVERIFY_RESULT % \
                    {"path":filename,
                     "result":_.LAB_ACCURATERIP_NOT_FOUND}
            else:
                for (confidence, ar_checksum, ar_crc2) in ar_matches:
                    if (checksum == ar_checksum):
                        self.summary_match.setdefault(track_type,
                                                      Counter()).increment()
                        return _.LAB_TRACKVERIFY_RESULT % \
                            {"path":filename,
                             "result":u"%s (%s)" %
                             (_.LAB_ACCURATERIP_FOUND,
                              _.LAB_ACCURATERIP_CONFIDENCE %
                              (confidence))}
                else:
                    self.summary_mismatch.setdefault(track_type,
                                                     Counter()).increment()
                    return _.LAB_TRACKVERIFY_RESULT % \
                        {"path":filename,
                         "result":_.LAB_ACCURATERIP_MISMATCH}
        else:
            #FIXME - display actual error
            self.summary_error.setdefault(track_type, Counter()).increment()
            return u"read error"

    def add_image_matches(self, filename, track_number, checksums):
        self.matches[(filename, track_number)] = checksums[:]

    def display_image(self, result):
        (filename, track_number, track_type, checksum, error) = result
        path = u"%s - track %2.2d" % (filename, track_number)
        if (error is None):
            ar_matches = self.matches.get((filename, track_number), [])
            if (len(ar_matches) == 0):
                self.summary_notfound.setdefault(track_type,
                                                 Counter()).increment()
                return _.LAB_TRACKVERIFY_RESULT % \
                    {"path":path,
                     "result":_.LAB_ACCURATERIP_NOT_FOUND}
            else:
                for (confidence, ar_checksum, ar_crc2) in ar_matches:
                    if (checksum == ar_checksum):
                        self.summary_match.setdefault(track_type,
                                                      Counter()).increment()
                        return _.LAB_TRACKVERIFY_RESULT % \
                            {"path":path,
                             "result":u"%s (%s)" %
                             (_.LAB_ACCURATERIP_FOUND,
                              _.LAB_ACCURATERIP_CONFIDENCE %
                              (confidence))}
                else:
                    self.summary_mismatch.setdefault(track_type,
                                                     Counter()).increment()
                    return _.LAB_TRACKVERIFY_RESULT % \
                        {"path":path,
                         "result":_.LAB_ACCURATERIP_MISMATCH}
        else:
            #FIXME - display actual error
            self.summary_error.setdefault(track_type, Counter()).increment()
            return u"read error"


if (__name__ == '__main__'):
    parser = audiotools.OptionParser(
        usage=_.USAGE_TRACKVERIFY,
        version="Python Audio Tools %s" % (audiotools.VERSION))

    parser.add_option('-t', '--type',
                      action='append',
                      dest='accept_list',
                      metavar='type',
                      choices=audiotools.TYPE_MAP.keys(),
                      help=_.OPT_TYPE_TRACKVERIFY)

    parser.add_option('-S', '--no-summary',
                      action='store_true',
                      dest='no_summary',
                      help=_.OPT_NO_SUMMARY)

    parser.add_option('-R', '--accuraterip',
                      action='store_true',
                      dest='accuraterip',
                      default=False,
                      help=_.OPT_ACCURATERIP)

    parser.add_option('-j', '--joint',
                      action='store',
                      type='int',
                      default=MAX_CPUS,
                      dest='max_processes',
                      help=_.OPT_JOINT)

    parser.add_option('-V', '--verbose',
                      action='store',
                      dest='verbosity',
                      choices=audiotools.VERBOSITY_LEVELS,
                      default=audiotools.DEFAULT_VERBOSITY,
                      help=_.OPT_VERBOSE)

    (options, args) = parser.parse_args()
    msg = audiotools.Messenger("trackverify", options)

    if (not options.accuraterip):
        queued_files = set([])  # a set of Filename objects already encountered
        results = Results(msg)
        queue = audiotools.ExecProgressQueue(audiotools.ProgressDisplay(msg))
        for track in get_tracks(args, queued_files, options.accept_list):
            queue.execute(
                function=verify,
                progress_text=unicode(audiotools.Filename(track.filename)),
                completion_output=results.display,
                track=track)

        msg.ansi_clearline()
        queue.run(options.max_processes)

        summary_success = results.summary_success
        summary_failure = results.summary_failure
        formats = sorted(list(set(summary_success.keys()) |
                              set(summary_failure.keys())))
        success_total = sum(map(int, summary_success.values()))
        failure_total = sum(map(int, summary_failure.values()))

        if ((len(formats) > 0) and (not options.no_summary)):
            msg.output(_.LAB_TRACKVERIFY_RESULTS)
            msg.output(u"")
            msg.new_row()
            msg.output_column(_.LAB_TRACKVERIFY_RESULT_FORMAT, True)
            msg.output_column(u" ")
            msg.output_column(_.LAB_TRACKVERIFY_RESULT_SUCCESS, True)
            msg.output_column(u" ")
            msg.output_column(_.LAB_TRACKVERIFY_RESULT_FAILURE, True)
            msg.output_column(u" ")
            msg.output_column(_.LAB_TRACKVERIFY_RESULT_TOTAL, True)
            msg.divider_row([u"-", u" ", u"-", u" ", u"-", u" ", u"-"])

            for format in formats:
                success = int(summary_success.get(format, 0))
                failure = int(summary_failure.get(format, 0))
                msg.new_row()
                msg.output_column(format.decode('ascii'), True)
                msg.output_column(u" ")
                msg.output_column(unicode(success), True)
                msg.output_column(u" ")
                msg.output_column(unicode(failure), True)
                msg.output_column(u" ")
                msg.output_column(unicode(success + failure), True)

            msg.divider_row([u"-", u" ", u"-", u" ", u"-", u" ", u"-"])
            msg.new_row()
            msg.output_column(_.LAB_TRACKVERIFY_SUMMARY, True)
            msg.output_column(u" ")
            msg.output_column(unicode(success_total), True)
            msg.output_column(u" ")
            msg.output_column(unicode(failure_total), True)
            msg.output_column(u" ")
            msg.output_column(unicode(success_total + failure_total), True)

            msg.output_rows()

        if (failure_total > 0):
            sys.exit(1)
    else:
        queued_files = set([])  # a set of Filename objects already encountered
        results = AccurateRipResults(msg)
        queue = audiotools.ExecProgressQueue(audiotools.ProgressDisplay(msg))

        for tracks in audiotools.group_tracks(
                get_tracks(args, queued_files, options.accept_list)):
            #perform AccurateRip lookup on album's worth of tracks
            #if tracks are CD formatted
            if ((set([t.channels() for t in tracks]) == set([2])) and
                (set([t.sample_rate() for t in tracks]) == set([44100])) and
                (set([t.bits_per_sample() for t in tracks]) == set([16]))):

                if ((len(tracks) == 1) and
                    (tracks[0].get_cuesheet() is not None)):
                    filename = audiotools.Filename(tracks[0].filename)
                    sheet = tracks[0].get_cuesheet()
                    total_frames = tracks[0].total_frames()
                    sample_rate = tracks[0].sample_rate()

                    #process tracks in CD image individually
                    ar_results = audiotools.accuraterip_sheet_lookup(
                        sheet, total_frames, sample_rate)

                    pcm_frames_offset = 0

                    for (i, pcm_frames) in enumerate(sheet.pcm_lengths(
                            total_frames, sample_rate), 1):
                        filename_string = u"track %2.2d" % (i)

                        results.add_image_matches(filename,
                                                  i,
                                                  ar_results.get(i, []))

                        queue.execute(
                            function=accuraterip_image_checksum,
                            progress_text=filename_string,
                            completion_output=results.display_image,
                            track=tracks[0],
                            filename=filename,
                            track_number=i,
                            pcm_frames_offset=pcm_frames_offset,
                            total_pcm_frames=pcm_frames)

                        pcm_frames_offset += pcm_frames
                else:
                    #process each track as if it were a CD
                    tracks = audiotools.sorted_tracks(tracks)
                    ar_results = audiotools.accuraterip_lookup(tracks)

                    for (i, track) in enumerate(tracks, 1):
                        filename = audiotools.Filename(track.filename)

                        results.add_matches(
                            filename,
                            ar_results.get(track_number(track, i), []))

                        queue.execute(
                            function=accuraterip_checksum,
                            progress_text=unicode(filename),
                            completion_output=results.display,
                            track=track)
            else:
                for track in tracks:
                    msg.error(u"\"%(path)s\" %(result)s" %
                              {"path":audiotools.Filename(track.filename),
                               "result":_.ERR_TRACKVERIFY})

        msg.ansi_clearline()
        queue.run(options.max_processes)

        summary_headers = []
        summaries = []

        if (sum(map(int, results.summary_match.values()))):
            summary_headers.append(_.LAB_TRACKVERIFY_ACCURATERIP_MATCH)
            summaries.append(results.summary_match)
        if (sum(map(int, results.summary_mismatch.values()))):
            summary_headers.append(_.LAB_TRACKVERIFY_ACCURATERIP_MISMATCH)
            summaries.append(results.summary_mismatch)
        if (sum(map(int, results.summary_notfound.values()))):
            summary_headers.append(_.LAB_TRACKVERIFY_ACCURATERIP_NOTFOUND)
            summaries.append(results.summary_notfound)
        if (sum(map(int, results.summary_error.values()))):
            summary_headers.append(_.LAB_TRACKVERIFY_ACCURATERIP_ERROR)
            summaries.append(results.summary_error)

        formats = sorted(reduce(or_,
                                [set(s.keys()) for s in summaries],
                                set([])))

        error_total = sum(map(int, results.summary_error.values()))

        divider_row = []

        if ((len(formats) > 0) and (not options.no_summary)):
            msg.output(_.LAB_TRACKVERIFY_RESULTS)
            msg.output(u"")

            msg.new_row()
            msg.output_column(_.LAB_TRACKVERIFY_RESULT_FORMAT, True)
            divider_row.append(u"-")
            for header in summary_headers:
                msg.output_column(u" ")
                msg.output_column(header, True)
                divider_row.extend([u" ", u"-"])
            msg.output_column(u" ")
            msg.output_column(_.LAB_TRACKVERIFY_RESULT_TOTAL, True)
            divider_row.extend([u" ", u"-"])
            msg.divider_row(divider_row)

            for format in formats:
                msg.new_row()
                msg.output_column(format.decode('ascii'), True)
                for summary in summaries:
                    msg.output_column(u" ")
                    msg.output_column(unicode(int(summary.get(format, 0))),
                                      True)
                msg.output_column(u" ")
                msg.output_column(unicode(sum([int(s.get(format, 0))
                                               for s in summaries])), True)

            msg.divider_row(divider_row)
            msg.new_row()
            msg.output_column(_.LAB_TRACKVERIFY_SUMMARY, True)
            for summary in summaries:
                msg.output_column(u" ")
                msg.output_column(unicode(sum(map(int, summary.values()))),
                                  True)
            msg.output_column(u" ")
            msg.output_column(
                unicode(sum([sum(map(int, s.values())) for s in summaries])),
                True)

            msg.output_rows()

        if (error_total > 0):
            sys.exit(1)
