.TH "audiotools.cfg" 5 "August 24, 2009" "" "Audio Tools Config File"
.SH NAME
audiotools.cfg \- configuration data for Python Audio Tools
.SH DESCRIPTION
The format of this file consists of one or more sections.
Each section contains one or more \fCkey: value\fR pairs.
.TS
tab(:);
| c | c | c |
| r | r | l |.
_
Section:Key:Value
=
\fC[MusicBrainz]\fR:\fCserver\fR:default MusicBrainz hostname
\^:\fCport\fR:default MusicBrainz port
_
\fC[FreeDB]\fR:\fCserver\fR:default FreeDB hostname
\^:\fCport\fR:default FreeDB port
_
\fC[System]\fR:\fCcdrom\fR:the default CD-ROM device to use
\^:\^:for CD reading/writing
\^:\fCcdrom_read_offset\fR:the sample offset to apply
\^:\^:when reading tracks
\^:\fCmaximum_jobs\fR:the maximum amount of processes
\^:\^:to run simultaneously
\^:\fCfs_encoding\fR:the filesystem's text encoding,
\^:\^:for reading/writing filenames
\^:\fCio_encoding\fR:the terminal's text encoding,
\^:\^:when generating screen output
_
\fC[Filenames]\fR:\fCformat\fR:the default filename template
_
\fC[Binaries]\fR:\fCflac\fR:the \fCflac\fR executable to use
\^:\^:for encoding/decoding FLAC files
\^:\fClame\fR:the \fClame\fR executable to use
\^:\^:for encoding/decoding MP3 files
\^:...:which executable to use
\^:\^:other than the default
_
\fC[Thumbnail]\fR:\fCformat\fR:the image format to use
\^:\^:such as `jpeg' or `png'
\^:\fCsize\fR:the maximum size of each thumbnail
_
.TE
.SH FORMAT STRING FIELDS
These fields are replace by actual track data when creating new filenames.
All other text is left as-is.
.TS
tab(:);
| c | c |
| l | l |.
_
Key:Value
=
\fC%(track_number)2.2d\fR:the track's number on the CD
\fC%(track_total)d\fR:the total number of tracks on the CD
\fC%(album_number)d\fR:the CD's album number
\fC%(album_total)d\fR:the total number of CDs in the set
\fC%(album_track_number)s\fR:combination of album and track number
\fC%(track_name)s\fR:the track's name
\fC%(album_name)s\fR:the album's name
\fC%(artist_name)s\fR:the track's artist name
\fC%(performer_name)s\fR:the track's performer name
\fC%(composer_name)s\fR:the track's composer name
\fC%(conductor_name)s\fR:the track's conductor name
\fC%(media)s\fR:the track's source media
\fC%(ISRC)s\fR:the track's ISRC
\fC%(catalog)s\fR:the track's catalog number
\fC%(copyright)s\fR:the track's copyright information
\fC%(publisher)s\fR:the track's publisher
\fC%(year)s\fR:the track's publication year
\fC%(date)s\fR:the track's original recording date
\fC%(suffix)s\fR:the track's suffix
\fC%(basename)s\fR:the track's original name, without suffix
_
.TE
.SH SEE ALSO
.BR audiotools-config (1),
.BR cd2track (1),
.BR cd2xmcd (1),
.BR cdinfo (1),
.BR coverdump (1),
.BR coverview (1),
.BR editxmcd (1),
.BR record2track (1),
.BR track2cd (1),
.BR track2xmcd (1),
.BR trackcat (1),
.BR trackcmp (1),
.BR trackinfo (1),
.BR tracklength (1),
.BR tracklint (1),
.BR trackplay (1),
.BR trackrename (1),
.BR tracksplit (1),
.BR tracktag (1)
.SH AUTHOR
Brian Langenberger
