Building the documentation PDFs requires the following:
* Python
  http://www.python.org
** reportlab Python library
   http://www.reportlab.com
* pdflatex
  http://www.tug.org/texlive/
* sphinx-build
  http://sphinx.pocoo.org/
* fig2dev
  http://www.xfig.org/
* gnuplot
  http://www.gnuplot.info/
* graphviz
  http://www.graphviz.org
* pdftk
  http://www.pdfhacks.com/pdftk/
