.TH "coverview" 1 "September 15, 2007" "" "Cover Image Viewer"
.SH NAME
coverview \- display cover images
.SH SYNOPSIS
coverview <track 1> [track 2] ...
.SH DESCRIPTION
.PP
coverview displays cover images which are embedded in audio tracks.
.SH OPTIONS
.TP
\fB-h, --help\fR
Show a list of options and exit
.TP
\fB--version\fR
Show the program's version and exit

.SH SEE ALSO
.BR cd2track (1), 
.BR cd2xmcd (1), 
.BR coverdump (1), 
.BR editxmcd (1), 
.BR track2cd (1), 
.BR track2track (1), 
.BR track2xmcd (1), 
.BR trackcat (1), 
.BR trackcmp (1), 
.BR trackinfo (1), 
.BR tracklength (1), 
.BR trackplay (1), 
.BR trackrename (1), 
.BR tracktag (1)
.SH AUTHOR
.nf
Brian Langenberger
.f
