.TH "coverdump" 1 "September 15, 2007" "" "Cover Image Extractor"
.SH NAME
coverdump \- extracts cover images to files
.SH SYNOPSIS
coverdump [-d directory] <track>
.SH DESCRIPTION
.PP
coverdump takes an audio track and extracts all of its embedded
cover images to individual files.
.SH OPTIONS
.TP
\fB-h, --help\fR
Show a list of options and exit
.TP
\fB--version\fR
Show the program's version and exit
.TP
\fB-d \fIdirectory\fB, --dir=\fIdirectory\fR
The target directory for the extracted image files.
If none is given, the current working directory is used.
.TP
\fB-V \fIVERBOSITY\fB, --verbose=\fIVERBOSITY\fR
The level of output to display.
Choose between `normal', `quiet' and `debug'.
.SH SEE ALSO
.BR audiotools-config (1),
.BR audiotools.cfg (5),
.BR cd2track (1),
.BR cd2xmcd (1),
.BR cdinfo (1),
.BR cdplay (1),
.BR coverview (1),
.BR dvda2track (1),
.BR dvda2xmcd (1),
.BR dvdainfo (1),
.BR editxmcd (1),
.BR record2track (1),
.BR track2cd (1),
.BR track2track (1),
.BR track2xmcd (1),
.BR trackcat (1),
.BR trackcmp (1),
.BR trackinfo (1),
.BR tracklength (1),
.BR tracklint (1),
.BR trackplay (1),
.BR trackrename (1),
.BR tracksplit (1),
.BR tracktag (1),
.BR trackverify (1)
.SH AUTHOR
Brian Langenberger
