.TH "dvdainfo" 1 "February 2, 2011" "" "DVD-Audio Information"
.SH NAME
dvdainfo \- prints information about a DVD-Audio disc
.SH SYNOPSIS
dvdainfo [OPTIONS]
.SH DESCRIPTION
.PP
dvdainfo takes an AUDIO_TS directory and writes information about the
DVD-Audio to standard output.
This includes the specifications for each title,
the length of the tracks within each title and where those tracks
are located within the disc's AOB files.
.SH OPTIONS
.TP
\fB-h, --help\fR
Show a list of options and exit
.TP
\fB--version\fR
Show the program's version and exit
.TP
\fB-A \fIDIRECTORY\fB, --audio-ts=\fIDIRECTORY\fR
The DVD-Audio's AUDIO_TS directory
.SH SEE ALSO
.BR audiotools-config (1),
.BR audiotools.cfg (5),
.BR cd2track (1),
.BR cd2xmcd (1),
.BR cdinfo (1),
.BR cdplay (1),
.BR coverdump (1),
.BR coverview (1),
.BR dvda2track (1),
.BR dvda2xmcd (1),
.BR editxmcd (1),
.BR record2track (1),
.BR track2cd (1),
.BR track2track (1),
.BR track2xmcd (1),
.BR trackcat (1),
.BR trackcmp (1),
.BR trackinfo (1),
.BR tracklength (1),
.BR tracklint (1),
.BR trackplay (1),
.BR trackrename (1),
.BR tracksplit (1),
.BR tracktag (1),
.BR trackverify (1)
.SH AUTHOR
Brian Langenberger
