.TH "editxmcd" 1 "June 15, 2007" "" "Metadata Editor"
.SH NAME
editxmcd \- edits existing metadata files
.SH SYNOPSIS
editxmcd [OPTIONS] [track 1] [track 2] ...
.SH DESCRIPTION
.PP
editxmcd can edit existing MusicBrain XML or FreeDB XMCD files.
It does not perform MusicBrainz or FreeDB lookups.
.SH OPTIONS
.TP
\fB-h, --help\fR
Show a list of options and exit
.TP
\fB--version\fR
Show the program's version and exit
.TP
\fB-x \fIfilename\fB, --xmcd=\fIfilename\fR
The MusicBrainz XML or FreeDB XMCD file to edit.

.SH EXAMPLE
.LP
Edit the data in an existing \fIalbum.xmcd\fR:
.IP
.B editxmcd -x \fIalbum.xmcd

.SH SEE ALSO
.BR audiotools-config (1),
.BR audiotools.cfg (5),
.BR cd2track (1),
.BR cd2xmcd (1),
.BR cdinfo (1),
.BR cdplay (1),
.BR coverdump (1),
.BR coverview (1),
.BR dvda2track (1),
.BR dvda2xmcd (1),
.BR dvdainfo (1),
.BR record2track (1),
.BR track2cd (1),
.BR track2track (1),
.BR track2xmcd (1),
.BR trackcat (1),
.BR trackcmp (1),
.BR trackinfo (1),
.BR tracklength (1),
.BR tracklint (1),
.BR trackplay (1),
.BR trackrename (1),
.BR tracksplit (1),
.BR tracktag (1),
.BR trackverify (1)
.SH AUTHOR
Brian Langenberger
