.TH "editxmcd" 1 "June 15, 2007" "" "Metadata Editor"
.SH NAME
editxmcd \- edits new or existing XMCD metadata files
.SH SYNOPSIS
editxmcd [OPTIONS] [track 1] [track 2] ...
.SH DESCRIPTION
.PP
editxmcd can edit existing XMCD files, or take a list of audio tracks
and allows one to edit a new XMCD file from those tracks' metadata.
It does not perform FreeDB lookups.
.SH OPTIONS
.TP
\fB-h, --help\fR
Show a list of options and exit
.TP
\fB--version\fR
Show the program's version and exit
.TP
\fB-x \fIfilename\fB, --xmcd=\fIfilename\fR
The XMCD file to edit.
If the XMCD file exists, that file will be edited and any audio tracks
will be ignored.
If the XMCD file does not exist, audio metadata will be retrieved from
the given audio tracks and a new XMCD file will be created.
.SH EXAMPLES
.LP
Edit the data in an existing \fIalbum.xmcd\fR:
.IP
.B editxmcd -x \fIalbum.xmcd

.LP
Build a new file called \fIalbum.xmcd\fR from all of the WAVE
files in the current directory:
.IP
.B editxmcd -x \fIalbum.xmcd\fR *.wav

.SH SEE ALSO
.BR cd2track (1),
.BR cd2xmcd (1),
.BR coverdump (1),
.BR coverview (1),
.BR record2track (1),
.BR track2cd (1),
.BR track2track (1),
.BR track2xmcd (1),
.BR trackcat (1),
.BR trackcmp (1),
.BR trackinfo (1),
.BR tracklength (1),
.BR tracklint (1),
.BR trackplay (1),
.BR trackrename (1),
.BR tracksplit (1),
.BR tracktag (1)
.SH AUTHOR
Brian Langenberger
