.TH "record2track" 1 "Jan 16, 2008" "" "Audio Recorder"
.SH NAME
record2track \- record audio to track
.SH SYNOPSIS
record2track [OPTIONS] ...
.SH DESCRIPTION
.PP
record2track records audio from an external source and saves it to a track.
.SH OPTIONS
.TP
\fB-h, --help\fR
Show a list of options and exit
.TP
\fB--version\fR
Show the program's version and exit
.SH AUTHOR
.nf
Brian Langenberger
.f

