.TH "track2xmcd" 1 "June 15, 2007" "" "Audio File Metadata Retriever"
.SH NAME
track2xmcd \- retrieves metadata from audio tracks
.SH SYNOPSIS
track2xmcd [OPTIONS] <track 1> [track 2] ...
.SH DESCRIPTION
.PP
track2xmcd takes a list of audio tracks and retrieves an XMCD file
containing their metadata such as track name, album name and artist.
By default, the MusicBrainz service is queried first.
If no matches are found, the FreeDB service is queried next.
If no data is found on either, an empty MusicBrainz XML file is
written which can be edited by the user.
.SH OPTIONS
.TP
\fB-h, --help\fR
Show a list of options and exit
.TP
\fB--version\fR
Show the program's version and exit
.TP
\fB-V \fIVERBOSITY\fB, --verbose=\fIVERBOSITY\fR
The level of output to display.
Choose between `normal', `quiet' and `debug'.
.TP
\fB-x \fIfilename\fB, --xmcd=\fIfilename\fR
The file in which MusicBrainz XML or FreeDB XMCD data will be placed.
.BR track2xmcd (1)
will refuse to overwrite an existing file if present.
If no filename is given, data will be written to
standard output.
.TP
\fB-m, --metadata\fR
Obtain XML or XMCD data from the given tracks rather than obtaining it
from a MusicBrainz or FreeDB server
.TP
\fB--cue=\fIFILENAME\fR
The cuesheet to use for track boundaries when attempting to
retrieve metadata from a CD image
.SH SERVER OPTIONS
.TP
\fB--musicbrainz-server=\fIserver\fR
The MusicBrainz server name to query for XML data
.TP
\fB--musicbrainz-port=\fIport\fR
The MusicBrainz port number to query for XML data
.TP
\fB--freedb-server=\fIserver\fR
The FreeDB server name to query for XMCD data
.TP
\fB--freedb-port=\fIport\fR
The FreeDB port number to query for XMCD data
.TP
\fB--no-musicbrainz\fR
Do not query MusicBrainz
.TP
\fB--no-freedb\fR
Do not query FreeDB
.TP
\fB-D, --default\fR
If multiple matching discs are found, select the first choice automatically

.SH EXAMPLES
.LP
Obtain an XMCD file called \fIalbum.xmcd\fR from all the WAVE
files in the current directory:
.IP
.B track2xmcd \-x
.I album.xmcd *.wav

.LP
Obtain an XMCD file called \fIalbum.xmcd\fR from \fICDImage.wav\fR
and \fICDImage.cue\fR:
.IP
.B track2xmcd \-x
.I album.xmcd
.B --cue=\fICDImage.cue\fR
.I CDImage.wav

.LP
Build an XMCD file from FLAC metadata and write it to standard output:
.IP
.B track2xmcd \-m
.I *.flac

.SH SEE ALSO
.BR audiotools-config (1),
.BR audiotools.cfg (5),
.BR cd2track (1),
.BR cd2xmcd (1),
.BR cdinfo (1),
.BR cdplay (1),
.BR coverdump (1),
.BR coverview (1),
.BR dvda2track (1),
.BR dvda2xmcd (1),
.BR dvdainfo (1),
.BR editxmcd (1),
.BR record2track (1),
.BR track2cd (1),
.BR track2track (1),
.BR trackcat (1),
.BR trackcmp (1),
.BR trackinfo (1),
.BR tracklength (1),
.BR tracklint (1),
.BR trackplay (1),
.BR trackrename (1),
.BR tracksplit (1),
.BR tracktag (1),
.BR trackverify (1)
.SH AUTHOR
Brian Langenberger
