.TH "trackinfo" 1 "June 15, 2007" "" "Track Information"
.SH NAME
trackinfo \- prints information and metadata from tracks
.SH SYNOPSIS
trackinfo [OPTIONS] <track 1> [track 2] ...
.SH DESCRIPTION
.PP
trackinfo takes a list of audio tracks and writes information about 
them to standard output.
This includes track length, number of channels, sample rate,
bits-per-sample, filename and additional metadata, if any.
.SH OPTIONS
.TP
\fB-h, --help\fR
Show a list of options and exit
.TP
\fB--version\fR
Show the program's version and exit
.TP
\fB-n, --no-metadata\fR
Do not print track metadata such as track name, album name and so forth
.TP
\fB-b, --bitrate\fR
Prints the average bitrate of the track in kilobytes-per-second
instead of the usual track information

.SH SEE ALSO
.BR cd2track (1), 
.BR cd2xmcd (1), 
.BR coverdump (1), 
.BR coverview (1), 
.BR editxmcd (1), 
.BR record2track (1), 
.BR track2cd (1), 
.BR track2track (1), 
.BR track2xmcd (1), 
.BR trackcat (1), 
.BR trackcmp (1), 
.BR tracklength (1), 
.BR trackplay (1), 
.BR trackrename (1), 
.BR tracktag (1)
.SH AUTHOR
.nf
Brian Langenberger
.f
