#FIXME - reorganize this big mess
ID3v22 = \
figures/id3v22/com.pdf \
figures/id3v22/geo.pdf \
figures/id3v22/pic.pdf \
figures/id3v22/t__.pdf \
figures/id3v22/txx.pdf \
figures/id3v22/ult.pdf \
figures/id3v22/w__.pdf \
figures/id3v22/wxx.pdf

ID3v23 = \
figures/id3v23/apic.pdf \
figures/id3v23/comm.pdf \
figures/id3v23/geob.pdf \
figures/id3v23/t___.pdf \
figures/id3v23/txxx.pdf \
figures/id3v23/uslt.pdf \
figures/id3v23/w___.pdf \
figures/id3v23/wxxx.pdf

ID3v24 = \
figures/id3v24/apic.pdf \
figures/id3v24/comm.pdf \
figures/id3v24/geob.pdf \
figures/id3v24/t___.pdf \
figures/id3v24/txxx.pdf \
figures/id3v24/uslt.pdf \
figures/id3v24/w___.pdf \
figures/id3v24/wxxx.pdf

FLAC = \
figures/flac/application.pdf \
figures/flac/block_header.pdf \
figures/flac/cuesheet.pdf \
figures/flac/fixed.pdf \
figures/flac/fixed2.pdf \
figures/flac/fixed-parse.pdf \
figures/flac/frame.pdf \
figures/flac/frames.pdf \
figures/flac/header-example.pdf \
figures/flac/lag0.pdf \
figures/flac/lag1.pdf \
figures/flac/lag2.pdf \
figures/flac/lag3.pdf \
figures/flac/lpc.pdf \
figures/flac/lpc2.pdf \
figures/flac/lpc-parse.pdf \
figures/flac/lpc-parse2.pdf \
figures/flac/metadata.pdf \
figures/flac/picture.pdf \
figures/flac/read_utf8.pdf \
figures/flac/residual.pdf \
figures/flac/residual-example1.pdf \
figures/flac/residual-example2.pdf \
figures/flac/residual-example3.pdf \
figures/flac/residual-example4.pdf \
figures/flac/residual-example5.pdf \
figures/flac/residual-parse.pdf \
figures/flac/seektable.pdf \
figures/flac/stream.pdf \
figures/flac/stream2.pdf \
figures/flac/stream3.pdf \
figures/flac/streaminfo.pdf \
figures/flac/subframes.pdf \
figures/flac/tukey.pdf \
figures/flac/utf8.pdf \
figures/flac/verbatim.pdf \
figures/flac/vorbiscomment.pdf \
figures/flac/write_utf8.pdf \
figures/oggflac_stream.pdf \
figures/utf-8-1.pdf \
figures/utf-8-2.pdf \
figures/utf-8-3.pdf

M4A = figures/m4a/quicktime.pdf \
figures/m4a/atom.pdf \
figures/m4a/atom2.pdf \
figures/m4a/atoms.pdf \
figures/m4a/data.pdf \
figures/m4a/disk.pdf \
figures/m4a/dref.pdf \
figures/m4a/ftyp.pdf \
figures/m4a/hdlr.pdf \
figures/m4a/mdhd.pdf \
figures/m4a/meta.pdf \
figures/m4a/meta_atoms.pdf \
figures/m4a/mp4a.pdf \
figures/m4a/mvhd.pdf \
figures/m4a/smhd.pdf \
figures/m4a/stco.pdf \
figures/m4a/stsc.pdf \
figures/m4a/stsd.pdf \
figures/m4a/stsz.pdf \
figures/m4a/stts.pdf \
figures/m4a/tkhd.pdf \
figures/m4a/trkn.pdf

WAVPACK = figures/wavpack/bitstream.pdf \
figures/wavpack/block_channels.pdf \
figures/wavpack/block_header.pdf \
figures/wavpack/block_header_parse.pdf \
figures/wavpack/channel_info.pdf \
figures/wavpack/decoding_params.pdf \
figures/wavpack/decorr_samples.pdf \
figures/wavpack/decorr_samples2.pdf \
figures/wavpack/decorr_samples_parse.pdf \
figures/wavpack/decorr_terms.pdf \
figures/wavpack/decorr_weights.pdf \
figures/wavpack/decorr_weights_parse.pdf \
figures/wavpack/decorrelation0.pdf \
figures/wavpack/decorrelation1.pdf \
figures/wavpack/decorrelation2.pdf \
figures/wavpack/decorrelation3.pdf \
figures/wavpack/decorrelation4.pdf \
figures/wavpack/decorrelation5.pdf \
figures/wavpack/entropy_vars.pdf \
figures/wavpack/entropy_vars_parse.pdf \
figures/wavpack/extended_integers.pdf \
figures/wavpack/md5sum.pdf \
figures/wavpack/pcm_sandwich.pdf \
figures/wavpack/read_residual.pdf \
figures/wavpack/read_residual1.pdf \
figures/wavpack/read_residual2.pdf \
figures/wavpack/read_residual3.pdf \
figures/wavpack/read_zeroes.pdf \
figures/wavpack/residuals_parse.pdf \
figures/wavpack/stream.pdf \
figures/wavpack/stream2.pdf \
figures/wavpack/subblock.pdf \
figures/wavpack/subblock_header.pdf \
figures/wavpack/subblock_parse.pdf \
figures/wavpack/terms_parse.pdf \
figures/wavpack/wave_footer.pdf \
figures/wavpack/wave_header.pdf \
figures/wavpack/write_zeroes.pdf

SHORTEN = figures/shorten/diff.pdf \
figures/shorten/qlpc.pdf \
figures/shorten/sandwich.pdf \
figures/shorten/signed.pdf \
figures/shorten/stream.pdf \
figures/shorten/unsigned.pdf \
figures/shorten/verbatim.pdf

ALAC = figures/alac/alac_atom.pdf \
figures/alac/alac-atom-parse.pdf \
figures/alac/atom.pdf \
figures/alac/atoms.pdf \
figures/alac/mdhd.pdf \
figures/alac/mdhd-parse.pdf \
figures/alac/residual-build.pdf \
figures/alac/residual-parse.pdf \
figures/alac/stream.pdf \
figures/alac/subframe-build.pdf \
figures/alac/subframe-parse.pdf \
figures/alac/subframe_header.pdf

MLP = figures/mlp/channel_parameters.pdf \
figures/mlp/codebook1.pdf \
figures/mlp/codebook2.pdf \
figures/mlp/codebook3.pdf \
figures/mlp/decoding_params.pdf \
figures/mlp/filter_params_fir.pdf \
figures/mlp/filter_params_iir.pdf \
figures/mlp/major_sync.pdf \
figures/mlp/matrix_params.pdf \
figures/mlp/output_shifts.pdf \
figures/mlp/parameter_presence_flags.pdf \
figures/mlp/quant_steps.pdf \
figures/mlp/residuals.pdf \
figures/mlp/restart_header.pdf \
figures/mlp/stream.pdf \
figures/mlp/substream.pdf \
figures/mlp/substream_size.pdf

DVDA = figures/dvda/aob_mlp_payload.pdf \
figures/dvda/aob_pack_header.pdf \
figures/dvda/aob_pcm_payload.pdf \
figures/dvda/ats_sectors.pdf \
figures/dvda/ats_title.pdf \
figures/dvda/ats_xx_0.pdf \
figures/dvda/ats_xx_x.pdf \
figures/dvda/audio_ts_ifo.pdf \
figures/dvda/layout.pdf

AOBPCM = figures/aobpcm/24bps_1ch.pdf \
figures/aobpcm/24bps_2ch.pdf \
figures/aobpcm/24bps_3ch.pdf \
figures/aobpcm/24bps_4ch.pdf \
figures/aobpcm/24bps_5ch.pdf \
figures/aobpcm/24bps_6ch.pdf

VORBIS = figures/ogg_packets.pdf \
figures/ogg_stream.pdf \
figures/vorbis/codebooks.pdf \
figures/vorbis/comment.pdf \
figures/vorbis/float32.pdf \
figures/vorbis/huffman_example1.pdf \
figures/vorbis/huffman_example2.pdf \
figures/vorbis/huffman_example3.pdf \
figures/vorbis/huffman_example4.pdf \
figures/vorbis/identification.pdf \
figures/vorbis/ordered_entries.pdf \
figures/vorbis/setup_packet.pdf


FIGURES = figures/binary.pdf figures/pcm.pdf figures/wav_stream.pdf \
figures/wav_fmt.pdf figures/wav_fmtext.pdf figures/wav_data.pdf \
figures/aiff_stream.pdf figures/aiff_comm.pdf figures/aiff_ssnd.pdf \
figures/au_stream.pdf \
figures/mp3_stream.pdf figures/mp3_xing.pdf \
figures/mp3_id3v1.pdf figures/mp3_id3v11.pdf \
figures/mp3_id3v2_stream.pdf \
figures/mp3_id3v22_header.pdf figures/mp3_id3v22_frame.pdf \
figures/mp3_id3v23_header.pdf figures/mp3_id3v23_frame.pdf \
figures/mp3_id3v24_header.pdf figures/mp3_id3v24_frame.pdf \
figures/mp3_id3v24_textframe.pdf figures/mp3_id3v24_apic.pdf \
figures/ape_stream.pdf figures/ape_descriptor.pdf figures/ape_header.pdf \
figures/apev2_tag.pdf figures/apev2_tagheader.pdf figures/apev2_flags.pdf \
figures/speex_header.pdf \
figures/musepack_sv7_stream.pdf figures/musepack_sv8_stream.pdf \
figures/musepack_sv8_sh.pdf figures/musepack_sv8_rg.pdf \
figures/musepack_sv8_ei.pdf figures/musepack_sv8_nut.pdf \
figures/freedb_sequence.pdf figures/freedb_discid.pdf \
figures/musicbrainz_discid.pdf figures/musicbrainz_xml.pdf \
figures/bitstream_struct.pdf figures/bitstream_bigendian.pdf \
figures/bitstream_littleendian.pdf figures/bitstream_littleendian_alt.pdf \
$(FLAC) \
$(M4A) \
$(ID3v22) \
$(ID3v23) \
$(ID3v24) \
$(WAVPACK) \
$(VORBIS) \
$(SHORTEN) \
$(ALAC) \
$(MLP) \
$(DVDA) \
$(AOBPCM)


CHAPTERS = basics.tex wav.tex flac.tex m4a.tex mp3.tex vorbis.tex \
wavpack.tex ape.tex aiff.tex au.tex speex.tex oggflac.tex musepack.tex \
freedb.tex musicbrainz.tex musicbrainz_mmd.tex replaygain.tex references.tex \
license.tex introduction.tex shorten.tex alac.tex mlp.tex dvda.tex

all: audioformats-letter.pdf audioformats-a4.pdf

clean:
	rm -f *.toc *.aux *.log *.out $(FIGURES)
	rm -f figures/pcm.fig figures/flac/tukey.fig
	rm -f audiotools-a4.tex audiotools-letter.tex

audioformats-letter.pdf: audioformats-letter.tex $(CHAPTERS) $(FIGURES)
	python pdflatexbuild.py -halt-on-error audioformats-letter.tex
	python ../pdftag.py "--title=Audio Formats Reference" "--author=Brian Langenberger" $@

audioformats-a4.pdf: audioformats-a4.tex $(CHAPTERS) $(FIGURES)
	python pdflatexbuild.py -halt-on-error audioformats-a4.tex
	python ../pdftag.py "--title=Audio Formats Reference" "--author=Brian Langenberger" $@

MP3_FIGURES = figures/mp3_stream2.pdf figures/mp3_frame_header.pdf \
figures/mp3_side_data_1ch.pdf figures/mp3_side_data_2ch.pdf \
figures/mp3_granule.pdf figures/mp3_main.pdf figures/mp3_scalefactors.pdf

mp3_decode.pdf: mp3_decode.tex $(MP3_FIGURES)
	python pdflatexbuild.py -halt-on-error $<

flac-codec.pdf: flac-codec.tex flac.tex $(FLAC)
	python pdflatexbuild.py -halt-on-error $<

alac-codec.pdf: alac-codec.tex alac.tex $(ALAC)
	python pdflatexbuild.py -halt-on-error $<

wavpack-codec.pdf: wavpack-codec.tex wavpack.tex $(WAVPACK)
	python pdflatexbuild.py -halt-on-error $<

audioformats-letter.tex: audioformats.m4
	m4 -D PAPERSIZE=letterpaper $< > $@

audioformats-a4.tex: audioformats.m4
	m4 -D PAPERSIZE=a4paper $< > $@

# binary.pdf: binary.fig
# 	fig2dev -L pdf binary.fig binary.pdf

figures/pcm.pdf: figures/pcm.fig
	fig2dev -Z 3 -L pdf $< $@

figures/pcm.fig: figures/pcm.plot
	./figures/pcm.plot > $@

figures/flac/tukey.pdf: figures/flac/tukey.fig
	fig2dev -Z 3 -L pdf $< $@

figures/flac/tukey.fig: figures/flac/tukey.plot
	./figures/flac/tukey.plot > $@

figures/utf-8-1.pdf: figures/utf-8-1.fig
	fig2dev -Z 3 -L pdf $< $@

figures/utf-8-2.pdf: figures/utf-8-2.fig
	fig2dev -Z 4 -L pdf $< $@

figures/utf-8-3.pdf: figures/utf-8-3.fig
	fig2dev -Z 5 -L pdf $< $@

figures/flac/lag0.pdf: figures/flac/lag0.fig
	fig2dev -Z 3.5 -L pdf $< $@

figures/flac/lag1.pdf: figures/flac/lag1.fig
	fig2dev -Z 3.5 -L pdf $< $@

figures/flac/lag2.pdf: figures/flac/lag2.fig
	fig2dev -Z 3.5 -L pdf $< $@

figures/flac/lag3.pdf: figures/flac/lag3.fig
	fig2dev -Z 3.5 -L pdf $< $@

figures/freedb_sequence.pdf: figures/freedb_sequence.fig
	fig2dev -Z 4 -L pdf $< $@

figures/musicbrainz_xml.pdf: figures/musicbrainz_xml.fig
	fig2dev -Z 4 -L pdf $< $@

figures/m4a/atoms.pdf: figures/m4a/atoms.fig
	fig2dev -Z 6 -L pdf $< $@

figures/m4a/meta_atoms.pdf: figures/m4a/meta_atoms.fig
	fig2dev -Z 3 -L pdf $< $@

figures/alac/atoms.pdf: figures/alac/atoms.fig
	fig2dev -Z 5 -L pdf $< $@

figures/bitstream_bigendian.pdf: figures/bitstream_bigendian.fig
	fig2dev -Z 6 -L pdf $< $@

figures/bitstream_littleendian.pdf: figures/bitstream_littleendian.fig
	fig2dev -Z 6 -L pdf $< $@

figures/bitstream_littleendian_alt.pdf: figures/bitstream_littleendian_alt.fig
	fig2dev -Z 6 -L pdf $< $@

figures/vorbis/ordered_entries.pdf: figures/vorbis/ordered_entries.dot
	dot -Tpdf $< -o $@

.SUFFIXES: .pdf .bdx .bpx .dot

.bdx.pdf:
	./bitdiagram.py -i $< -o $@

.bpx.pdf:
	./bitparse.py -i $< -o $@

.dot.pdf:
	dot -Tpdf $< -o $@

figures/m4a/ftyp.pdf: figures/m4a/ftyp.bdx
	./bitdiagram.py -w 270 -i $< -o $@

figures/m4a/mvhd.pdf: figures/m4a/mvhd.bdx
	./bitdiagram.py -w 270 -i $< -o $@

figures/m4a_meta.pdf: figures/m4a_meta.bdx
	./bitdiagram.py -w 306 -i $< -o $@

figures/m4a_data.pdf: figures/m4a_data.bdx
	./bitdiagram.py -w 306 -i $< -o $@

figures/alac/atom.pdf: figures/m4a/atom.bdx
	./bitdiagram.py -w 324 -i $< -o $@

figures/alac/alac-atom-parse.pdf: figures/alac/alac-atom-parse.bpx
	./bitparse.py -w 480 -b 24 -i $< -o $@

figures/alac/mdhd.pdf: figures/m4a/mdhd.bdx
	./bitdiagram.py -i $< -o $@

# figures/alac/subframe-parse.pdf: figures/alac/subframe-parse.bpx
# 	./bitparse.py -w 500 -b 24 -i $< -o $@

figures/alac/subframe-parse.pdf: figures/alac/subframe-parse.bpx
	./bitparse.py -w 432 -b 16 -i $< -o $@

figures/alac/residual-parse.pdf: figures/alac/residual-parse.bpx
	./bitparse.py -w 490 -b 24 -i $< -o $@

figures/alac/residual-build.pdf: figures/alac/residual-build.bpx
	./bitparse.py -w 490 -b 24 -i $< -o $@

figures/shorten/unsigned.pdf: figures/shorten/unsigned.fig
	fig2dev -Z 2 -L pdf $< $@

figures/shorten/signed.pdf: figures/shorten/signed.fig
	fig2dev -Z 2 -L pdf $< $@

# figures/wavpack/block_header_parse.pdf: figures/wavpack/block_header_parse.bpx
# 	./bitparse.py -w 480 -b 24 -i $< -o $@

figures/wavpack/decorrelation0.fig: figures/wavpack/decorrelation1.plot figures/wavpack/decorr_pass0.dat
	./figures/wavpack/decorrelation0.plot > $@

figures/wavpack/decorrelation0.pdf: figures/wavpack/decorrelation0.fig
	fig2dev -Z 3 -L pdf $< $@

figures/wavpack/decorrelation1.fig: figures/wavpack/decorrelation1.plot figures/wavpack/decorr_pass1.dat
	./figures/wavpack/decorrelation1.plot > $@

figures/wavpack/decorrelation1.pdf: figures/wavpack/decorrelation1.fig
	fig2dev -Z 3 -L pdf $< $@

figures/wavpack/decorrelation2.fig: figures/wavpack/decorrelation2.plot
	./figures/wavpack/decorrelation2.plot > $@

figures/wavpack/decorrelation2.pdf: figures/wavpack/decorrelation2.fig
	fig2dev -Z 3 -L pdf $< $@

figures/wavpack/decorrelation3.fig: figures/wavpack/decorrelation3.plot
	./figures/wavpack/decorrelation3.plot > $@

figures/wavpack/decorrelation3.pdf: figures/wavpack/decorrelation3.fig
	fig2dev -Z 3 -L pdf $< $@

figures/wavpack/decorrelation4.fig: figures/wavpack/decorrelation4.plot
	./figures/wavpack/decorrelation4.plot > $@

figures/wavpack/decorrelation4.pdf: figures/wavpack/decorrelation4.fig
	fig2dev -Z 3 -L pdf $< $@

figures/wavpack/decorrelation5.fig: figures/wavpack/decorrelation5.plot
	./figures/wavpack/decorrelation5.plot > $@

figures/wavpack/decorrelation5.pdf: figures/wavpack/decorrelation5.fig
	fig2dev -Z 3 -L pdf $< $@

figures/wavpack/residuals_parse.pdf: figures/wavpack/residuals_parse.bpx
	./bitparse.py -i $< -o $@ -b 24 -w 480

figures/flac/utf8.pdf: figures/flac/utf8.bpx
	./bitparse.py -i $< -o $@ -b 8 -w 170

figures/flac/lpc-parse2.pdf: figures/flac/lpc-parse2.bpx
	./bitparse.py -i $< -o $@ -b 24 -w 480
